version: "3.9"

networks:
  default:
    external: false
  traefik-gateway:
    external: true

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - xanity-mongodb-data:/data/db
    networks:
      - default

  backend:
    image: ghcr.io/saizaax/xanity-backend:latest
    environment:
      - PORT=5050
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=xanity
      - JWT_SECRET=SECRET
      - JWT_EXPIRE_HOURS=24h
    depends_on:
      - mongodb
    networks:
      - default

  frontend:
    image: ghcr.io/saizaax/xanity-frontend:latest
    depends_on:
      - backend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.http.routers.xanity.rule=Host(`example.com`)"
        - "traefik.http.routers.xanity.entrypoints=websecure"
        - "traefik.http.routers.xanity.tls.certresolver=letsencrypt"
        - "traefik.http.routers.xanity.tls=true"
        - "traefik.http.services.xanity.loadbalancer.server.port=80"
    networks:
      - traefik-gateway
      - default

volumes:
  xanity-mongodb-data: