services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongodbdata:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - PORT=5050
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=xanity
      - JWT_SECRET=3ma3gK0xKPz81iQCUAcmtkvIWjjrXkLo
      - JWT_EXPIRE_HOURS=24h
    ports:
      - 5050:5050
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: "frontend"
    ports:
      - 3000:3000
    depends_on:
      - backend

  proxy: 
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend